server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    hikari:
      maximum-pool-size: 1
      minimum-idle: 0
    url: jdbc:mysql://mysql-1e26ae34-tuitentu131-e142.g.aivencloud.com:18003/shopping?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: avnadmin
    password: AVNS_b4Ayu0j9wQLl_83CZvm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/ecommerce-realm

# Mã hóa AES yêu cầu khóa 256-bit (32 bytes). Trong thực tế sẽ được load từ Vault
encryption:
  aes:
    key: "32_byte_long_secret_key_for_aes!" 

hmac_secret: default_secret_fallback_do_not_use_in_prod
