server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # Custom ReactiveJwtDecoder bean handles local token validation
          issuer-uri: http://localhost:9090/realms/ecommerce-realm
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # Next.js frontend
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: catalog-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
            - PrefixPath=/api
        - id: cart-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/cart/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payments/**
