server:
  port: 8084

spring:
  application:
    name: payment-service
  cloud:
    vault:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=UTC
    username: ecomuser
    password: ecompassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/ecommerce-realm

# Fallback value, will be overridden by Vault (secret/ecommerce)
hmac_secret: default_secret_fallback_do_not_use_in_prod
