server:
  port: 8082
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/cart_db?useSSL=false&serverTimezone=UTC
    username: ecomuser
    password: ecompassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/ecommerce-realm
