server:
  port: 8081
spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mysql://mysql-1e26ae34-tuitentu131-e142.g.aivencloud.com:18003/shopping?useSSL=true&requireSSL=true&serverTimezone=UTC
    username: avnadmin
    password: AVNS_b4Ayu0j9wQL1_83CZvm
  jpa:
    hibernate:
      ddl-auto: update
