export const MOCK_PRODUCTS = [
  { id: 1, name: 'iPhone 15 Pro Max', description: 'Apple Smartphone 256GB Titanium', price: 29000000, category: 'Smartphone', stock: 50, imageUrl: '/picture.png' },
  { id: 2, name: 'Samsung Galaxy S24 Ultra', description: 'Samsung Flagship AI Phone 512GB', price: 31000000, category: 'Smartphone', stock: 30, imageUrl: '/picture.png' },
  { id: 3, name: 'Google Pixel 8 Pro', description: 'Google Pure Android Camera Phone', price: 25000000, category: 'Smartphone', stock: 25, imageUrl: '/picture.png' },
  { id: 4, name: 'Xiaomi 14 Pro', description: 'Xiaomi Leica Camera Flagship', price: 22000000, category: 'Smartphone', stock: 40, imageUrl: '/picture.png' },
  { id: 5, name: 'Oppo Find X7 Ultra', description: 'Oppo Hasselblad Camera Phone', price: 26000000, category: 'Smartphone', stock: 15, imageUrl: '/picture.png' },
  { id: 6, name: 'Sony Xperia 1 V', description: 'Sony Professional Camera Phone', price: 32000000, category: 'Smartphone', stock: 10, imageUrl: '/picture.png' },
  { id: 7, name: 'Asus ROG Phone 8', description: 'Asus Ultimate Gaming Phone', price: 28000000, category: 'Smartphone', stock: 20, imageUrl: '/picture.png' },
  { id: 8, name: 'iPhone 15', description: 'Apple Base Model 128GB', price: 20000000, category: 'Smartphone', stock: 100, imageUrl: '/picture.png' },
  { id: 9, name: 'Samsung Galaxy Z Fold 5', description: 'Samsung Premium Foldable Phone', price: 40000000, category: 'Smartphone', stock: 15, imageUrl: '/picture.png' },
  { id: 10, name: 'Samsung Galaxy Z Flip 5', description: 'Samsung Compact Foldable Phone', price: 22000000, category: 'Smartphone', stock: 35, imageUrl: '/picture.png' },

  { id: 11, name: 'MacBook Pro 16 M3 Max', description: 'Apple Laptop for Professionals 36GB RAM', price: 85000000, category: 'Laptop', stock: 10, imageUrl: '/picture.png' },
  { id: 12, name: 'MacBook Air 15 M3', description: 'Apple Thin & Light Laptop 16GB', price: 35000000, category: 'Laptop', stock: 40, imageUrl: '/picture.png' },
  { id: 13, name: 'Dell XPS 15 9530', description: 'Dell Premium Windows Laptop i9', price: 55000000, category: 'Laptop', stock: 20, imageUrl: '/picture.png' },
  { id: 14, name: 'Lenovo ThinkPad X1 Carbon Gen 11', description: 'Lenovo Business Laptop', price: 45000000, category: 'Laptop', stock: 30, imageUrl: '/picture.png' },
  { id: 15, name: 'Asus Zephyrus G14', description: 'Asus Compact Gaming Laptop', price: 40000000, category: 'Laptop', stock: 25, imageUrl: '/picture.png' },
  { id: 16, name: 'Razer Blade 16', description: 'Razer Premium Gaming Laptop RTX 4080', price: 90000000, category: 'Laptop', stock: 5, imageUrl: '/picture.png' },
  { id: 17, name: 'HP Spectre x360', description: 'HP 2-in-1 Premium Laptop', price: 38000000, category: 'Laptop', stock: 20, imageUrl: '/picture.png' },
  { id: 18, name: 'LG Gram 17', description: 'LG Ultra Lightweight Laptop', price: 36000000, category: 'Laptop', stock: 15, imageUrl: '/picture.png' },
  { id: 19, name: 'Alienware m18', description: 'Alienware Desktop Replacement Laptop', price: 85000000, category: 'Laptop', stock: 8, imageUrl: '/picture.png' },
  { id: 20, name: 'Surface Laptop Studio 2', description: 'Microsoft Professional Hybrid Laptop', price: 65000000, category: 'Laptop', stock: 12, imageUrl: '/picture.png' },

  { id: 21, name: 'iPad Pro 12.9 M2', description: 'Apple Ultimate Tablet', price: 30000000, category: 'Tablet', stock: 40, imageUrl: '/picture.png' },
  { id: 22, name: 'iPad Air 5', description: 'Apple Mid-range Tablet', price: 15000000, category: 'Tablet', stock: 80, imageUrl: '/picture.png' },
  { id: 23, name: 'Samsung Galaxy Tab S9 Ultra', description: 'Samsung Ultimate Android Tablet', price: 28000000, category: 'Tablet', stock: 25, imageUrl: '/picture.png' },
  { id: 24, name: 'Xiaomi Pad 6 Max', description: 'Xiaomi Large Entertainment Tablet', price: 12000000, category: 'Tablet', stock: 50, imageUrl: '/picture.png' },
  { id: 25, name: 'Amazon Kindle Paperwhite', description: 'Amazon e-Reader', price: 3500000, category: 'Tablet', stock: 100, imageUrl: '/picture.png' },
  { id: 26, name: 'Boox Note Air 3', description: 'E-ink Tablet for Note Taking', price: 11000000, category: 'Tablet', stock: 20, imageUrl: '/picture.png' },
  { id: 27, name: 'Surface Pro 9', description: 'Microsoft Windows 2-in-1 Tablet', price: 25000000, category: 'Tablet', stock: 30, imageUrl: '/picture.png' },
  { id: 28, name: 'Lenovo Tab P12 Pro', description: 'Lenovo Premium Android Tablet', price: 18000000, category: 'Tablet', stock: 35, imageUrl: '/picture.png' },
  { id: 29, name: 'iPad Mini 6', description: 'Apple Compact Tablet', price: 13000000, category: 'Tablet', stock: 60, imageUrl: '/picture.png' },
  { id: 30, name: 'Remarkable 2', description: 'Digital Paper Tablet', price: 12000000, category: 'Tablet', stock: 15, imageUrl: '/picture.png' },

  { id: 31, name: 'AirPods Pro 2', description: 'Apple Noise Cancelling Earbuds', price: 6000000, category: 'Audio', stock: 150, imageUrl: '/picture.png' },
  { id: 32, name: 'AirPods Max', description: 'Apple Premium Over-ear Headphones', price: 12000000, category: 'Audio', stock: 30, imageUrl: '/picture.png' },
  { id: 33, name: 'Sony WH-1000XM5', description: 'Sony Industry Leading ANC Headphones', price: 8500000, category: 'Audio', stock: 60, imageUrl: '/picture.png' },
  { id: 34, name: 'Sony WF-1000XM5', description: 'Sony Premium Wireless Earbuds', price: 6500000, category: 'Audio', stock: 70, imageUrl: '/picture.png' },
  { id: 35, name: 'Bose QuietComfort Ultra', description: 'Bose Ultimate Comfort ANC Headphones', price: 9000000, category: 'Audio', stock: 40, imageUrl: '/picture.png' },
  { id: 36, name: 'Sennheiser Momentum 4', description: 'Sennheiser Audiophile Wireless Headphones', price: 8000000, category: 'Audio', stock: 25, imageUrl: '/picture.png' },
  { id: 37, name: 'Marshall Motif II ANC', description: 'Marshall Classic Design Earbuds', price: 4500000, category: 'Audio', stock: 50, imageUrl: '/picture.png' },
  { id: 38, name: 'Jabra Elite 8 Active', description: 'Jabra Sports Wireless Earbuds', price: 5000000, category: 'Audio', stock: 45, imageUrl: '/picture.png' },
  { id: 39, name: 'Samsung Galaxy Buds 2 Pro', description: 'Samsung High-Res Earbuds', price: 4000000, category: 'Audio', stock: 80, imageUrl: '/picture.png' },
  { id: 40, name: 'Devialet Gemini II', description: 'Devialet Luxury Wireless Earbuds', price: 11000000, category: 'Audio', stock: 10, imageUrl: '/picture.png' },

  { id: 41, name: 'Apple Watch Ultra 2', description: 'Apple Rugged Smartwatch', price: 20000000, category: 'Accessories', stock: 40, imageUrl: '/picture.png' },
  { id: 42, name: 'Apple Watch Series 9', description: 'Apple Daily Smartwatch', price: 10000000, category: 'Accessories', stock: 100, imageUrl: '/picture.png' },
  { id: 43, name: 'Samsung Galaxy Watch 6 Classic', description: 'Samsung Smartwatch with Bezel', price: 8000000, category: 'Accessories', stock: 60, imageUrl: '/picture.png' },
  { id: 44, name: 'Garmin Epix Pro', description: 'Garmin Ultimate Sports Watch', price: 25000000, category: 'Accessories', stock: 20, imageUrl: '/picture.png' },
  { id: 45, name: 'Garmin Fenix 7X', description: 'Garmin Adventure Watch', price: 22000000, category: 'Accessories', stock: 25, imageUrl: '/picture.png' },
  { id: 46, name: 'Anker 737 Power Bank', description: 'Anker 24000mAh 140W Charger', price: 3500000, category: 'Accessories', stock: 80, imageUrl: '/picture.png' },
  { id: 47, name: 'Apple MagSafe Charger', description: 'Apple Official Wireless Charger', price: 1200000, category: 'Accessories', stock: 200, imageUrl: '/picture.png' },
  { id: 48, name: 'Logitech MX Master 3S', description: 'Logitech Premium Productivity Mouse', price: 2500000, category: 'Accessories', stock: 120, imageUrl: '/picture.png' },
  { id: 49, name: 'Keychron Q1 Pro', description: 'Keychron Custom Mechanical Keyboard', price: 4500000, category: 'Accessories', stock: 50, imageUrl: '/picture.png' },
  { id: 50, name: 'Sony DualSense Edge', description: 'Sony Premium PS5 Controller', price: 5500000, category: 'Accessories', stock: 40, imageUrl: '/picture.png' }
];
